deploy infra

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,37 +2,42 @@ version: 2.1
 orbs:
   slack: circleci/slack@4.1
 
-# commands:
-#   destroy-environment:
-#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-#     parameters:
-#       # Add parameter here
-#     steps:
-#       - run:
-#           name: Destroy environments
-#           when: on_fail
-#           command: |
-#             # Your code here
-#             exit 1
+commands:
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      workflow_id:
+        type: string
+        # default: ${CIRCLE_WORKFLOW_ID}
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            aws cloudformation delete-stack \
+            --stack-name udapeole-backend-<<parameters.workflow_id>>
+            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
+            aws cloudformation delete-stack \
+            --stack-name udapeole-frontend-<<parameters.workflow_id>>
 
-# revert-migrations:
-#   description: Revert the last migration if successfully run in the current workflow.
-#   parameters:
-#     # Add parameter here
-#   steps:
-#     - run:
-#         name: Revert migrations
-#         # Add when this will run
-#         command: |
-#           # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-#           SUCCESS = 1
-#           if(( $SUCCESS==1 ));
-#           then
-#           #  cd ~/project/backend
-#           #  npm install
-#           #  Add revert code here. You can find this in the Getting Started section.
-#             exit 1
-#           fi
+revert-migrations:
+  description: Revert the last migration if successfully run in the current workflow.
+  parameters:
+    # Add parameter here
+  steps:
+    - run:
+        name: Revert migrations
+        # Add when this will run
+        command: |
+          # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+          SUCCESS = 1
+          if(( $SUCCESS==1 ));
+          then
+          #  cd ~/project/backend
+          #  npm install
+          #  Add revert code here. You can find this in the Getting Started section.
+            exit 1
+          fi
 
 jobs:
   build-frontend:
@@ -131,58 +136,60 @@ jobs:
           event: fail
           template: basic_fail_1
 
-  #   deploy-infrastructure:
-  #     docker:
-  #       # Docker image here that supports AWS CLI
-  #     steps:
-  #       # Checkout code from git
-  #       - run:
-  #           name: Ensure back-end infrastructure exists
-  #           command: |
-  #             aws cloudformation deploy \
-  #               --template-file .circleci/files/backend.yml \
-  #               #--tags project=your-tag \
-  #               # --stack-name "your back-end stack name with workflow id" \
-  #               # --parameter-overrides ID="your workflow id"
-  #               exit 1
-  #       - run:
-  #           name: Ensure front-end infrastructure exist
-  #           command: |
-  #             aws cloudformation deploy \
-  #               --template-file .circleci/files/frontend.yml \
-  #               #--tags project=your-tag \
-  #               # --stack-name "your front-end stack name with workflow id" \
-  #               # --parameter-overrides ID="your workflow id"
-  #               exit 1
-  #       - run:
-  #           name: Add back-end ip to ansible inventory
-  #           command: |
-  #             # Your code here
-  #             exit 1
-  #       - persist_to_workspace:
-  #           root: ~/
-  #           paths:
-  #             - project/.circleci/ansible/inventory.txt
-  #       # Here's where you will add some code to rollback on failure
+    deploy-infrastructure:
+      docker:
+        - image: amazon/aws-cli
+      steps:
+        - checkout
+        - run: yum install -y tar gzip
+        - run:
+            name: Ensure back-end infrastructure exists
+            command: |
+              aws cloudformation deploy \
+                --template-file .circleci/files/backend.yml \
+                --tags project=your-tag \
+                --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+                --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
+        - run:
+            name: Ensure front-end infrastructure exist
+            command: |
+              aws cloudformation deploy \
+                --template-file .circleci/files/frontend.yml \
+                --tags project=your-tag \
+                --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
+                --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
+        - run:
+            name: Add back-end ip to ansible inventory
+            command: |
+              echo $(aws ec2 decribe-instances) \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+              --output text) >> ~/project/.circleci/ansible/inventory.txt
+        - persist_to_workspace:
+            root: ~/
+            paths:
+              - project/.circleci/ansible/inventory.txt
+        - destroy-environment:
+            workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
-  #   configure-infrastructure:
-  #     docker:
-  #       # Docker image here that supports Ansible
-  #     steps:
-  #       # Checkout code from git
-  #       # Add ssh keys with fingerprint
-  #       # attach workspace
-  #       - run:
-  #           name: Install dependencies
-  #           command: |
-  #             # Your code here
-  #             exit 1
-  #       - run:
-  #           name: Configure server
-  #           command: |
-  #             # Your code here
-  #             exit 1
-  #       # Here's where you will add some code to rollback on failure
+    configure-infrastructure:
+      docker:
+        # Docker image here that supports Ansible
+      steps:
+        # Checkout code from git
+        # Add ssh keys with fingerprint
+        # attach workspace
+        - run:
+            name: Install dependencies
+            command: |
+              # Your code here
+              exit 1
+        - run:
+            name: Configure server
+            command: |
+              # Your code here
+              exit 1
+        # Here's where you will add some code to rollback on failure
 
   #   run-migrations:
   #     docker:
@@ -316,8 +323,8 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
-      # - deploy-infrastructure:
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       #     filters:
       #       branches:
       #         only: [test-feature-branch]
